services:
  - type: web
    name: user-service
    runtime: docker
    dockerfilePath: ./backend/UserService/Dockerfile
    dockerContext: ./backend/UserService
    plan: free
    healthCheckPath: /health
